services:
  financial-ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-ai-agent
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./dataset:/app/dataset
      - ./.env:/app/.env
    networks:
      - financial-network
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434/v1

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
      args:
        - OLLAMA_MODEL=${OLLAMA_MODEL}
    container_name: financial-ai-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - financial-network
    restart: unless-stopped

volumes:
  ollama-data:
    driver: local

networks:
  financial-network:
    driver: bridge
